name: toolkit
description: "Made by horn players!"
publish_to: 'none'
version: 0.2.5+17

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flame: ^1.11.0
  flutter:
    sdk: flutter
  pitch_detector_plus: ^0.0.8
  pitch_detector_dart: ^0.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  flutter_audio_capture: ^1.1.8
  wakelock_plus: ^1.2.8
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  #qr_code_scanner: ^1.0.1
  json_annotation: ^4.9.0
  #qr_code_dart_scan: ^0.9.3
  mobile_scanner: ^6.0.2
  provider: ^6.1.2
  logging: ^1.3.0
  supabase_flutter: ^2.8.4
  app_links: ^6.4.0
  flutter_riverpod: ^2.6.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
