name: toolkit
description: "Made by horn players!"
publish_to: 'none'
version: 0.1.4+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flame: ^1.11.0
  flutter:
    sdk: flutter
  pitch_detector_plus: ^0.0.8
  pitch_detector_dart: ^0.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.15
  flutter_audio_capture: ^1.1.7
  wakelock_plus: ^1.2.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
